CapaPresentacionAdmin/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;




namespace CapaPresentacionAdmin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarios()
        {
            List<Usuario> oLista = new List<Usuario>();

            oLista = new CN_Usuarios().listar();

            return Json(new {data = oLista }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult GuardarUsuario(Usuario objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdUsuario == 0)
            {
                resultado = new CN_Usuarios().registrar(objeto,out mensaje);
            }
            else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);
             
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
    }
}

CapaPresentacionAdmin/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }



        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> oLista = new List<Categoria>();

            oLista = new CN_Categoria().listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);

        }




        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdCategoria == 0)
            {
                resultado = new CN_Categoria().registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Categoria().Editar(objeto, out mensaje);

            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }




        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


    }
}

CapaPresentacionAdmin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

CapaPresentacionAdmin/Views/Home/Usuarios.cshtml
@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Resumen</a></li>
    <li class="breadcrumb-item active">Usuarios</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Lista De Usuarios
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />

        <!-- Contenedor responsivo para la tabla -->
        <div class="table-responsive">
            <table id="tabla" class="display cell-border" style="width:100%">
                <thead>
                    <tr>
                        <th>Nombres</th>
                        <th>Apellido</th>
                        <th>Correo</th>
                        <th>Activo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- La tabla se inicializa vacía -->
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-2">

                    <input id="txtid" type="hidden" value="0" />
                    <div class="col-sm-6">
                        <label for="txtnombres" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="txtnombres" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="txtapellidos" class="form-label">Apellidos</label>
                        <input type="text" class="form-control" id="txtapellidos" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="txtcorrreo" class="form-label">Correo</label>
                        <input type="text" class="form-control" id="txtcorrreo" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select class="form-select" id="cboactivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12">
                        <div class="alert alert-danger d-none" role="alert" id="mensajeError">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <!-- Estilos de DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css">

    <!-- Scripts de jQuery y DataTables -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js"></script>

    <!-- SweetAlert2 -->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        // Inicialización de DataTables con datos asíncronos
        let filaSeleccionada;
        let tabledata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            ajax: {
                url: "@Url.Action("ListarUsuarios", "Home")",
                type: 'GET',
                dataType: "json"
            },
            columns: [
                { data: "Nombres" },
                { data: "Apellidos" },
                { data: "Correo" },
                {
                    data: "Activo",
                    render: function (valor) {
                        return valor ? '<span class="badge bg-success">Si</span>' : '<span class="badge bg-danger">No</span>';
                    }
                },
                {
                    defaultContent: `
                        <button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1"></i></button>
                        <button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash me-1"></i></button>`,
                    orderable: false,
                    searchable: false,
                    width: "90px"
                }
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/2.1.8/i18n/es-ES.json"
            }
        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtnombres").val('');
            $("#txtapellidos").val('');
            $("#txtcorrreo").val('');
            $("#cboactivo").val(1);
            $("#mensajeError").hide();

            if (json != null) {
                $("#txtid").val(json.IdUsuario);
                $("#txtnombres").val(json.Nombres);
                $("#txtapellidos").val(json.Apellidos);
                $("#txtcorrreo").val(json.Correo);
                $("#cboactivo").val(json.Activo ? 1 : 0);
            }
            $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr");
            let data = tabledata.row(filaSeleccionada).data();
            abrirModal(data);
        });


        $("#tabla tbody").on("click", '.btn-eliminar', function () {
            let usuarioSeleccionado = $(this).closest("tr");

            let data = tabledata.row(usuarioSeleccionado).data();

            Swal.fire({
                title: "¿Estás seguro?",
                text: "¡No podrás revertir esto!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Sí, eliminar",
                cancelButtonText: "Cancelar"
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: "Eliminado",
                        text: "El usuario ha sido eliminado.",
                        icon: "success"
                    });

                    jQuery.ajax({
                        url: '@Url.Action("EliminarUsuario","Home")',
                        type: 'POST',
                        data: JSON.stringify({ id: data.IdUsuario }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado) {
                                tabledata.row(usuarioSeleccionado).remove().draw();
                            } else {
                                Swal.fire({
                                    icon: "error",
                                    title: "no se puedo eliminar el usuario",
                                    text: data.mensaje,
                                    footer: '<a href="#">Why do I have this issue?</a>',
                                    
                                });
                            }
                        } 

                    })

                }

            });
  

        });





        function Guardar() {
            let Usuario = {
                IdUsuario: $("#txtid").val(),
                Activo: $("#cboactivo").val() == 1,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorrreo").val(),
                Nombres: $("#txtnombres").val()
            };

            jQuery.ajax({
                url: '@Url.Action("GuardarUsuario", "Home")',
                type: "POST",
                data: JSON.stringify({ objeto: Usuario }),
                dataType: "json",
                contentType: "application/json; charset-utf-8",
                success: function (data) {
                    $(".modal-body").LoadingOverlay("hide");

                    if (Usuario.IdUsuario == 0) {
                        if (data.resultado != 0) {
                            Usuario.IdUsuario = data.resultado;
                            tabledata.row.add(Usuario).draw(false);
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    } else {
                        if (data.resultado) {
                            tabledata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function () {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show");
                }
            });
        }
    </script>
}

CapaPresentacionAdmin/Views/Mantenedor/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i> Lista De Categorias
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nueva</button>
            </div>
        </div>
        <hr />

        <!-- Contenedor responsivo para la tabla -->
        <div class="table-responsive">
            <table id="tabla" class="display cell-border" style="width:100%">
                <thead>
                    <tr>
                        <th>Descripcion</th>
                        <th>Activo</th>
                       
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!-- La tabla se inicializa vacía -->
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-1">

                

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select class="form-select" id="cboactivo">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-12">
                        <div class="alert alert-danger d-none" role="alert" id="mensajeError">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <!-- Estilos de DataTables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.dataTables.min.css">

    <!-- Scripts de jQuery y DataTables -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js"></script>

    <!-- SweetAlert2 -->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        // Inicialización de DataTables con datos asíncronos
        let filaSeleccionada;
        let tabledata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            ajax: {
                url: "@Url.Action("ListarCategoria", "Mantenedor")",
                type: 'GET',
                dataType: "json"
            },
            columns: [
               
                { data: "Descripcion" },
                {
                    data: "Activo",
                    render: function (valor) {
                        return valor ? '<span class="badge bg-success">Si</span>' : '<span class="badge bg-danger">No</span>';
                    }
                },
                {
                    defaultContent: `
                        <button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1"></i></button>
                        <button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash me-1"></i></button>`,
                    orderable: false,
                    searchable: false,
                    width: "90px"
                }
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/2.1.8/i18n/es-ES.json"
            }
        });

        function abrirModal(json) {
            $("#txtid").val(0);
            $("#txtDescripcion").val('');
            $("#cboactivo").val(1);
            $("#mensajeError").hide();

            if (json != null) {
                $("#txtid").val(json.IdCategoria);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cboactivo").val(json.Activo ? 1 : 0);
            }
            $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr");
            let data = tabledata.row(filaSeleccionada).data();
            abrirModal(data);
        });


        $("#tabla tbody").on("click", '.btn-eliminar', function () {
            let cateogoriaSeleccionada = $(this).closest("tr");

            let data = tabledata.row(cateogoriaSeleccionada).data();

            Swal.fire({
                title: "¿Estás seguro?",
                text: "¡No podrás revertir esto!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Sí, eliminar",
                cancelButtonText: "Cancelar"
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: "Eliminado",
                        text: "La Categoria ha sido eliminado.",
                        icon: "success"
                    });

                    jQuery.ajax({
                        url: '@Url.Action("EliminarCategoria", "Home")',
                        type: 'POST',
                        data: JSON.stringify({ id: data.IdUsuario }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado) {
                                tabledata.row(usuarioSeleccionado).remove().draw();
                            } else {
                                Swal.fire({
                                    icon: "error",
                                    title: "no se puedo eliminar la categoria",
                                    text: data.mensaje,
                                    footer: '<a href="#">Why do I have this issue?</a>',

                                });
                            }
                        }

                    })

                }

            });


        });





        function Guardar() {
            let Usuario = {
                IdUsuario: $("#txtid").val(),
                Activo: $("#cboactivo").val() == 1,
                Apellidos: $("#txtapellidos").val(),
                Correo: $("#txtcorrreo").val(),
                Nombres: $("#txtnombres").val()
            };

            jQuery.ajax({
                url: '@Url.Action("GuardarUsuario", "Home")',
                type: "POST",
                data: JSON.stringify({ objeto: Usuario }),
                dataType: "json",
                contentType: "application/json; charset-utf-8",
                success: function (data) {
                    $(".modal-body").LoadingOverlay("hide");

                    if (Usuario.IdUsuario == 0) {
                        if (data.resultado != 0) {
                            Usuario.IdUsuario = data.resultado;
                            tabledata.row.add(Usuario).draw(false);
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    } else {
                        if (data.resultado) {
                            tabledata.row(filaSeleccionada).data(Usuario).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function () {
                    $(".modal-body").LoadingOverlay("hide");
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show");
                }
            });
        }
    </script>
}

CapaPresentacionAdmin/Views/Mantenedor/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marca</h2>

CapaPresentacionAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body class="sb-nav-fixed">

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Mi tienda</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        @*<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>*@
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo Del Usuario</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrrar Sesion</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Resumen</div>
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link" href="@Url.Action("Usuarios","Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-circle"></i></div>
                            Usuarios
                        </a>
                        <div class="sb-sidenav-menu-heading">Mantenimiento</div>
                        <a class="nav-link" href="@Url.Action("Categoria","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorias
                        </a>
                        <a class="nav-link" href="@Url.Action("Marca","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Marcas
                        </a>
                        <a class="nav-link" href="@Url.Action("Producto","Mantenedor")">
                            <div class="sb-nav-link-icon"><i class="fas fa-product-hunt"></i></div>
                            Productos
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>



    @*<li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Pagina test", "PaginaTest", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/complementos")
    @RenderSection("scripts", required: false)
</body>
</html>